### ISSUE TITLE
Add ability to toggle "Toddler Lock" on/off.

### ISSUE THREAD

**Issue by rml1111** [dahlb/ha_hatch#19]
Thanks again for creating this integration. It has been working very well for me. I use the Rest+'s in my children's bedrooms and from time to time, the kids mess with the physical buttons on the device. It would be ideal to be able to switch on toddler lock from an HA automation similar to in the option when creating a schedule in the Hatch app (assuming the Rest+ API supports this).

**Comment by dahlb** [comment]
I looked into the child lock function, as I haven't used it before.  Hatch only allows it to be turned on using a scheduled program. I don't use the scheduled programs since I prefer to interact with it directly through automation scripts.  I am not interested in developing a service for modifying Hatch programs through HA.  

I'm closing this issue, sorry.
